############### Parameters associated with the data ###############
input:

  # as of right now, we only support a single experiment
  # with a forward and reverse component
  samples:
    forward: '/home/zamc8857/animal_svs/data/samples/larger1.fq'
    reverse: '/home/zamc8857/animal_svs/data/samples/larger2.fq'

  # reference genome database
  reference: '/home/zamc8857/animal_svs/data/house-sparrow.fa'

  # used to name output files. Not needed. If left blank, 
  # defaults to the filename of the forward sequence
  sample_name: 'cloud-test-local'

############### Parameters associated with the run ###############
run:
  
  # temporary file store. Files will be deleted
  temp_dir: '../temp'

  # output any issues/progress to this location
  logs_dir: '../logs'

  # directory to save final output files
  output_dir: '/home/zamc8857/animal_svs/data/output'

  # for deployment either locally or to the cloud
  deployment:
    
    # supported types: 'cloud', 'local'
    type: 'local'

    # Service is ONLY used if deployment is set to 'cloud'
    # current supported services are: 'gcp'
    service: 'gcp'

    # if deployment is cloud, we assume that files are stored in the cloud
    # therefore we need the bucket name. As of right now, we only support
    # storage that is the same as the deployment. So if deployment is 'gcp', 
    # data must be stored in a gcp bucket. do NOT add the gs:// or s3:// prefix
    bucket_name: 'vc_pipeline_bucket'
